name: Hello World

on:
  repository_dispatch:
    types: [my-custom-event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Parameters
        run: |
          echo "Param1: ${{ github.event.client_payload.param1 }}"
          echo "Param2: ${{ github.event.client_payload.param2 }}"
